/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GraphsRouteImport } from './routes/graphs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BorrowersIndexRouteImport } from './routes/borrowers.index'
import { Route as BorrowersBorrowerIdRouteImport } from './routes/borrowers.$borrowerId'
import { Route as BorrowersNewRouteImport } from './routes/borrowers.new'
import { Route as LoanIndexRouteImport } from './routes/loan.index'
import { Route as LoanLoanIdRouteImport } from './routes/loan.$loanId'
import { Route as LoanNewRouteImport } from './routes/loan.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsRoute = GraphsRouteImport.update({
  id: '/graphs',
  path: '/graphs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowersIndexRoute = BorrowersIndexRouteImport.update({
  id: '/borrowers/',
  path: '/borrowers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowersBorrowerIdRoute = BorrowersBorrowerIdRouteImport.update({
  id: '/borrowers/$borrowerId',
  path: '/borrowers/$borrowerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowersNewRoute = BorrowersNewRouteImport.update({
  id: '/borrowers/new',
  path: '/borrowers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanIndexRoute = LoanIndexRouteImport.update({
  id: '/loan/',
  path: '/loan/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanLoanIdRoute = LoanLoanIdRouteImport.update({
  id: '/loan/$loanId',
  path: '/loan/$loanId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanNewRoute = LoanNewRouteImport.update({
  id: '/loan/new',
  path: '/loan/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/dashboard': typeof DashboardRoute
  '/graphs': typeof GraphsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/borrowers/$borrowerId': typeof BorrowersBorrowerIdRoute
  '/borrowers/new': typeof BorrowersNewRoute
  '/loan/$loanId': typeof LoanLoanIdRoute
  '/loan/new': typeof LoanNewRoute
  '/borrowers/': typeof BorrowersIndexRoute
  '/loan/': typeof LoanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/dashboard': typeof DashboardRoute
  '/graphs': typeof GraphsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/borrowers/$borrowerId': typeof BorrowersBorrowerIdRoute
  '/borrowers/new': typeof BorrowersNewRoute
  '/loan/$loanId': typeof LoanLoanIdRoute
  '/loan/new': typeof LoanNewRoute
  '/borrowers': typeof BorrowersIndexRoute
  '/loan': typeof LoanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/dashboard': typeof DashboardRoute
  '/graphs': typeof GraphsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/borrowers/$borrowerId': typeof BorrowersBorrowerIdRoute
  '/borrowers/new': typeof BorrowersNewRoute
  '/loan/$loanId': typeof LoanLoanIdRoute
  '/loan/new': typeof LoanNewRoute
  '/borrowers/': typeof BorrowersIndexRoute
  '/loan/': typeof LoanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/dashboard'
    | '/graphs'
    | '/settings'
    | '/sitemap.xml'
    | '/borrowers/$borrowerId'
    | '/borrowers/new'
    | '/loan/$loanId'
    | '/loan/new'
    | '/borrowers/'
    | '/loan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/dashboard'
    | '/graphs'
    | '/settings'
    | '/sitemap.xml'
    | '/borrowers/$borrowerId'
    | '/borrowers/new'
    | '/loan/$loanId'
    | '/loan/new'
    | '/borrowers'
    | '/loan'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/dashboard'
    | '/graphs'
    | '/settings'
    | '/sitemap.xml'
    | '/borrowers/$borrowerId'
    | '/borrowers/new'
    | '/loan/$loanId'
    | '/loan/new'
    | '/borrowers/'
    | '/loan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  DashboardRoute: typeof DashboardRoute
  GraphsRoute: typeof GraphsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BorrowersBorrowerIdRoute: typeof BorrowersBorrowerIdRoute
  BorrowersNewRoute: typeof BorrowersNewRoute
  LoanLoanIdRoute: typeof LoanLoanIdRoute
  LoanNewRoute: typeof LoanNewRoute
  BorrowersIndexRoute: typeof BorrowersIndexRoute
  LoanIndexRoute: typeof LoanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs': {
      id: '/graphs'
      path: '/graphs'
      fullPath: '/graphs'
      preLoaderRoute: typeof GraphsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrowers/': {
      id: '/borrowers/'
      path: '/borrowers'
      fullPath: '/borrowers/'
      preLoaderRoute: typeof BorrowersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrowers/$borrowerId': {
      id: '/borrowers/$borrowerId'
      path: '/borrowers/$borrowerId'
      fullPath: '/borrowers/$borrowerId'
      preLoaderRoute: typeof BorrowersBorrowerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrowers/new': {
      id: '/borrowers/new'
      path: '/borrowers/new'
      fullPath: '/borrowers/new'
      preLoaderRoute: typeof BorrowersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/': {
      id: '/loan/'
      path: '/loan'
      fullPath: '/loan/'
      preLoaderRoute: typeof LoanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/$loanId': {
      id: '/loan/$loanId'
      path: '/loan/$loanId'
      fullPath: '/loan/$loanId'
      preLoaderRoute: typeof LoanLoanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/new': {
      id: '/loan/new'
      path: '/loan/new'
      fullPath: '/loan/new'
      preLoaderRoute: typeof LoanNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  DashboardRoute: DashboardRoute,
  GraphsRoute: GraphsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BorrowersBorrowerIdRoute: BorrowersBorrowerIdRoute,
  BorrowersNewRoute: BorrowersNewRoute,
  LoanLoanIdRoute: LoanLoanIdRoute,
  LoanNewRoute: LoanNewRoute,
  BorrowersIndexRoute: BorrowersIndexRoute,
  LoanIndexRoute: LoanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
